version: "3.9"
services:
  backend:
    image: "mrrolbot/springboot-react-fullstack:2.5.2022.6.59.30"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
