version: "3.9"
services:
  backend:
    image: "mrrolbot/springboot-react-fullstack:7.5.2022.21.41.18"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
